### ISSUE TITLE
Any dependency on Ruby ?

### ISSUE THREAD

**Issue by mostafaasad** [unswmedicine/erica_engineer_interview_task_003_public#1]
What are the dependencies need to be consider to do the deployment successfully?

**Comment by greenaussie** [comment]
I tested this on a clean Ubuntu 20.04 live VM (which, as it happens, does not have ruby language installed).

The only things I installed were:

- docker
- git
- vim

**Comment by mostafaasad** [comment]
No problem, I am using Mac and it’s ok

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by greenaussie** [comment]
OK great.
